sudo: false
language: go


#go:
#  - 1.4

# Need to specify this explicitly because we have a Makefile.
install: go get ./cmd/... ./ github.com/robustirc/bridge/robustirc-bridge

script: go test ./...
