sudo: false
language: go


#go:
#  - 1.4

# Need to specify this explicitly because we have a Makefile.
# TODO: remove last one
install:
  - go get ./cmd/... ./ github.com/robustirc/bridge/robustirc-bridge github.com/robustirc/robustirc
# Hotfix. TODO: send PR
  - sed -i 's/^\s*return \(strings.Replace.*\)/return strings.Replace(\1, "-", "_", -1)/g' $GOPATH/src/github.com/armon/go-metrics/prometheus.go

script: go test ./...

after_failure: head -500 /tmp/robustirc*/stderr.txt
