language: go

go:
  - tip

# Need to specify this explicitly because we have a Makefile.
install: go get github.com/robustirc/robustirc/cmd/... github.com/robustirc/robustirc

script: go test github.com/robustirc/robustirc/...
