sudo: false
language: go


#go:
#  - 1.4

env:
  - GOMAXPROCS=2

# Need to specify this explicitly because we have a Makefile.
# TODO: remove last one
install:
  # Hotfix. TODO: send PR
  - go get -d github.com/armon/go-metrics
  - sed -i 's/^\s*return \(strings.Replace.*\)/return strings.Replace(\1, "-", "_", -1)/g' $HOME/gopath/src/github.com/armon/go-metrics/prometheus.go
  - go get ./cmd/... ./ github.com/robustirc/bridge/robustirc-bridge github.com/robustirc/robustirc

script:
  - go test ./...
  # Check whether files are syntactically correct.
  - echo $(find . -name "*.go" | tr '\n' ' ')
  - gofmt -l $(find . -name "*.go" | tr '\n' ' ') >/dev/null
  # Check whether files were not gofmt'ed.
  - "[ $(gofmt -l $(find . -name '*.go' | tr '\\n' ' ') | wc -l) -eq 0 ] || (echo 'gofmt was not run on these files:'; gofmt -l $(find . -name '*.go' | tr '\\n' ' ') 2>/dev/null; false)"

after_failure: head -500 /tmp/robustirc*/stderr.txt
